In [1]:
""" 
Section 1 - 2026 Grad Colloquium Learning Package
=====================================================
Description: This notebook will help beginner coders open and inspect data - seciton 2 of the accompanying handbook - wokring with CSV files

Version History: 22/05/26, written by A.D. & Claude, 11/06/26 A.D. write script

Notes:
"""

' \nSection 1 - 2026 Grad Colloquium Learning Package\n=====================================================\nDescription: This notebook will help beginner coders open and inspect data - seciton 2 of the accompanying handbook - wokring with CSV files\n\nVersion History: 22/05/26, written by A.D. & Claude, 11/06/26 A.D. write script\n\nNotes:\n'

In [2]:
import xarray as xr         # NetCDF & multi-dimensional data

import numpy as np           # numerical operations
import matplotlib.pyplot as plt  # plotting
from glob import glob #global path directory

In [10]:
df = pd.read_csv("")

# Always start by inspecting:
print(df.head())         # first 5 rows
print(df.dtypes)         # column data types
print(df.describe())     # summary statistics
print(df.shape)          # (rows, columns)

         time assigned_SWT
0  1952-01-01         WH-A
1  1952-01-02         TH-A
2  1952-01-03         FH-A
3  1952-01-04        WCT-A
4  1952-01-05        WCT-A
time            object
assigned_SWT    object
dtype: object
              time assigned_SWT
count        26937        26937
unique       26937           30
top     1952-01-01         TH-A
freq             1         1299
(26937, 2)

             time assigned_SWT
0      1952-01-01         WH-A
1      1952-01-02         TH-A
2      1952-01-03         FH-A
3      1952-01-04        WCT-A
4      1952-01-05        WCT-A
...           ...          ...
26932  2025-09-26         FH-B
26933  2025-09-27         EH-D
26934  2025-09-28        WCT-B
26935  2025-09-29        COL-B
26936  2025-09-30         WH-D

[26937 rows x 2 columns]

In [12]:
# Option 2: convert after loading
df[""] = pd.to_datetime(df["time"])

# Set time as the index for easy slicing
df = df.set_index("time")
print(df.head())

           assigned_SWT
time
1952-01-01         WH-A
1952-01-02         TH-A
1952-01-03         FH-A
1952-01-04        WCT-A
1952-01-05        WCT-A

In [24]:
# Select a single column
test = df[""] #here, we define a shorthand term “cf” to represent capacity_factor column
test

time
1952-01-01     WH-A
1952-01-02     TH-A
1952-01-03     FH-A
1952-01-04    WCT-A
1952-01-05    WCT-A
              ...
2025-09-26     FH-B
2025-09-27     EH-D
2025-09-28    WCT-B
2025-09-29    COL-B
2025-09-30     WH-D
Name: assigned_SWT, Length: 26937, dtype: object

In [25]:
# Filter rows by date range
summer = df["2020-11-01":""] #now, if we use “summer” instead of “df”, we can run all our code for summertime only
summer

           assigned_SWT
time
2020-11-01        COL-F
2020-11-02         TH-B
2020-11-03         FH-A
2020-11-04         WH-A
2020-11-05         WH-A
...                 ...
2020-12-27         AM-A
2020-12-28         AM-A
2020-12-29         AM-C
2020-12-30         AM-C
2020-12-31         AM-C

[61 rows x 1 columns]

### Edit this snippet to find out how many COL-F days are in the whole dataframe compared to the summer of 2020/2021

In [29]:
# Filter rows by a condition
cloudy = df[df["capacity_factor"] < 0.5]
print(f"Cloudy days: {len(cloudy)}")

KeyError: 'capacity_factor'